use("ecommerce_backend");

db.getCollectionNames();
db.getCollection("products").insertMany([
  {
    title: "Smartphone Stand",
    description: "Adjustable aluminum phone stand for desk",
    price: 299.0,
    category: "electronics",
    stock: 50,
    images: ["https://example.com/phone-stand.jpg"],
  },
  {
    title: "Denim Jacket",
    description: "Stylish blue denim jacket for men",
    price: 999.00,
    category: "clothing",
    stock: 30,
    images: ["https://example.com/denim-jacket.jpg"],
  },
  {
    title: "Wooden Coffee Table",
    description: "Solid wood modern coffee table for living room",
    price: 1500.0,
    category: "furniture",
    stock: 10,
    images: ["https://example.com/coffee-table.jpg"],
  },
  {
    title: "Wireless Mouse",
    description: "Ergonomic Bluetooth mouse with silent clicks",
    price: 549.00,
    category: "electronics",
    stock: 40,
    images: ["https://example.com/wireless-mouse.jpg"],
  },
  {
    title: "Fantasy Novel: Dragon’s Curse",
    description: "Epic fantasy book with dragons, magic, and mystery",
    price: 499.00,
    category: "books",
    stock: 100,
    images: ["https://example.com/dragons-curse.jpg"],
  },
  {
    title: "Men’s Running Shoes",
    description: "Lightweight breathable running shoes",
    price: 899.00,
    category: "clothing",
    stock: 25,
    images: ["https://example.com/running-shoes.jpg"],
  },
  {
    title: "Bluetooth Speaker",
    description: "Portable waterproof speaker with deep bass",
    price: 1999.00,
    category: "electronics",
    stock: 60,
    images: ["https://example.com/bluetooth-speaker.jpg"],
  },
  {
    title: "Office Chair",
    description: "Ergonomic mesh chair with lumbar support",
    price: 5500.00,
    category: "furniture",
    stock: 15,
    images: ["https://example.com/office-chair.jpg"],
  },
  {
    title: "Sketchbook Set",
    description: "A3-sized drawing pad with premium paper",
    price: 350.00,
    category: "other",
    stock: 35,
    images: ["https://example.com/sketchbook.jpg"],
  },
  {
    title: "Cookbook: Quick Meals",
    description: "Over 100 easy and delicious recipes",
    price: 799.00,
    category: "books",
    stock: 80,
    images: ["https://example.com/cookbook.jpg"],
  },
  {
    title: "Yoga Mat",
    description: "Non-slip eco-friendly yoga mat",
    price: 899.00,
    category: "other",
    stock: 45,
    images: ["https://example.com/yoga-mat.jpg"],
  },
]);
